version: '2'

volumes:
  clash-out:
  v2ray-mtp:
  frp-in:

services:
  clash-out:
    image: dreamacro/clash:latest
    ports:
      - 42103:32103
      - 42104:7999
    restart: always
    volumes:
      - /root/clash-docker-compose/clash:/root/.config/clash

  v2ray-mtp:
    image: v2fly/v2fly-core:latest
    ports:
      - 42101:32101
      - 42102:32102
    links:
      - clash-out
    volumes:
      - /root/clash-docker-compose/v2ray.json:/etc/v2ray/config.json
    restart: always
  frp-in:
    image: snowdreamtech/frps:latest
    ports:
      - 42100:32100
      - 42200:32200
    volumes:
      - /root/clash-docker-compose/frps.ini:/etc/frp/frps.ini
    restart: always